version: '3'

services:
  db:
    image: mysql:8.0.21
    container_name: dt_db
    platform: linux/x86_64
    ports:
      - 33065:3306
    environment:
      - MYSQL_ROOT_PASSWORD=admin
    restart: 'always'
